# Generated by Django 3.2.10 on 2022-10-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallOlder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full name')),
                ('email', models.CharField(max_length=500, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=500, verbose_name='Phone')),
                ('current_balance', models.FloatField(verbose_name='Balance')),
                ('last_payment', models.DateTimeField(verbose_name='Last payment')),
                ('reg_date', models.DateTimeField(verbose_name='Data')),
                ('lastcall_date', models.DateTimeField(verbose_name='Last call')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'call older',
                'verbose_name_plural': 'call olders',
            },
        ),
        migrations.CreateModel(
            name='ClientsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full name')),
                ('email', models.CharField(max_length=500, verbose_name='Email')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=500, verbose_name='Phone')),
                ('current_balance', models.FloatField(verbose_name='Balance')),
                ('last_payment', models.DateTimeField(verbose_name='Last payment')),
                ('reg_date', models.DateTimeField(verbose_name='Data')),
                ('lastcall_date', models.DateTimeField(verbose_name='Last call')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ErrorClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full name')),
                ('email', models.CharField(max_length=500, verbose_name='Email')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=500, verbose_name='Phone')),
                ('current_balance', models.FloatField(verbose_name='Balance')),
                ('last_payment', models.DateTimeField(verbose_name='Last payment')),
                ('reg_date', models.DateTimeField(verbose_name='Data')),
                ('lastcall_date', models.DateTimeField(verbose_name='Last call')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'error client',
                'verbose_name_plural': 'error clients',
            },
        ),
        migrations.CreateModel(
            name='InactiveClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full name')),
                ('email', models.CharField(max_length=500, verbose_name='Email')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=500, verbose_name='Phone')),
                ('current_balance', models.FloatField(verbose_name='Balance')),
                ('last_payment', models.DateTimeField(verbose_name='Last payment')),
                ('reg_date', models.DateTimeField(verbose_name='Data')),
                ('lastcall_date', models.DateTimeField(verbose_name='Last call')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'inactive client',
                'verbose_name_plural': 'inactive clients',
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentNotOlder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full name')),
                ('email', models.CharField(max_length=500, verbose_name='Email')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=500, verbose_name='Phone')),
                ('current_balance', models.FloatField(verbose_name='Balance')),
                ('last_payment', models.DateTimeField(verbose_name='Last payment')),
                ('reg_date', models.DateTimeField(verbose_name='Data')),
                ('lastcall_date', models.DateTimeField(verbose_name='Last call')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'replenishment not older',
                'verbose_name_plural': 'replenishment not olders',
            },
        ),
    ]
