# Generated by Django 3.2.10 on 2022-10-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='address',
            new_name='address_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='current_balance',
            new_name='current_balance_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='email',
            new_name='email_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='full_name',
            new_name='full_name_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='last_payment',
            new_name='last_payment_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='lastcall_date',
            new_name='lastcall_date_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='phone_number',
            new_name='phone_number_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='reg_date',
            new_name='reg_date_i',
        ),
        migrations.RenameField(
            model_name='inactiveclients',
            old_name='status',
            new_name='status_i',
        ),
    ]
