# Generated by Django 3.2.10 on 2022-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20221007_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='callolder',
            name='address',
            field=models.CharField(default=1, max_length=500, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
